// Modified in 2026 for multilingual localization and VSCodium/Windows compatibility.
/**
 * Mysti localization helpers.
 * Runtime strings are translated with VS Code's native vscode.l10n API.
 * Russian translations live in l10n/bundle.l10n.ru.json, never in main code.
 */
import * as vscode from 'vscode';

export const t = vscode.l10n.t;

const WEBVIEW_MESSAGES = [
  "\"{0}\" too large (max {1})",
  "(click to change)",
  "(click to cycle)",
  "(not installed)",
  "(selection)",
  "+ Connect Channel",
  "... (truncated)",
  "... {0} more lines",
  "/brainstorm",
  "/clear",
  "/compact",
  "/exit-plan-mode",
  "/help",
  "1-9 to select · Enter to submit",
  "100-day streak",
  "3-day streak",
  "30-day streak",
  "7-day streak",
  "A browser window will open for authentication",
  "A powerful AI coding agent for VSCode supporting multiple backends.",
  "A powerful AI coding agent for VSCode supporting multiple backends. Mysti can analyze code, execute tasks, and collaborate with you on complex projects.",
  "AI Approved",
  "AI Denied",
  "AI answered on your behalf",
  "AI approved this action",
  "AI asks before each file change - balanced control and productivity",
  "AI can edit files autonomously - maximum speed for trusted tasks",
  "AI can only read files, never modify - safest option for exploring codebases",
  "AI can only read files, no modifications",
  "AI decides in",
  "AI decides in {0}",
  "AI decides when you don't respond in time.",
  "AI deciding...",
  "AI denied this action",
  "AI has full read/write access",
  "AI makes all decisions immediately. Destructive actions always blocked.",
  "AI makes an intelligent decision using safety classification and learned preferences when timeout expires",
  "AI selecting...",
  "AI will answer if no response",
  "AI will ask before making changes",
  "AI will ask permission before making changes",
  "AI will generate a detailed implementation plan",
  "AI will generate a quick implementation plan",
  "AI will make changes without asking",
  "AI will select an approach if no response",
  "AI {0} this action",
  "API Key",
  "API key for LocalAI (if authentication is configured on your server). Leave empty if not required.",
  "About Mysti",
  "Accept",
  "Access",
  "Access Level",
  "Access level",
  "Access level changed to: {0}",
  "Action was {0} due to timeout.",
  "Activate {0} different skills",
  "Active",
  "Active ({0} processes)",
  "Active ({0})",
  "Active Mode",
  "Active:",
  "Active: {0}",
  "Active: {0} (click to change)",
  "Activity",
  "Add Context",
  "Add Explicit Context",
  "Add Mysti to workspace recommendations",
  "Add a file to context",
  "Add any additional instructions or constraints...",
  "Add comprehensive test coverage",
  "Add custom instructions",
  "Add docs",
  "Add docs, comments & usage examples",
  "Add tests",
  "Add to Context",
  "Added {0} file(s) to context",
  "Added {0} line",
  "Added {0} lines",
  "Additional regex patterns to block in autonomous mode (e.g. dangerous commands)",
  "Adjust Claude thinking depth",
  "Adjust thinking depth",
  "Advanced reasoning for code, math, and STEM",
  "Advanced reasoning model",
  "Agent",
  "Agent Behavior",
  "Agent Configuration",
  "Agent Settings",
  "Agent asks before every change",
  "Agent edits files, you approve system actions",
  "Agent encountered an error",
  "Agent generates plans without executing changes",
  "Agent has file access, asks before complex changes",
  "Agent has full control over files and actions",
  "Agent session shut down",
  "Agent shutdown blocked: {0}",
  "Agent shutdown blocked: {0} active child processes",
  "Agent to use for synthesis in brainstorm mode",
  "Agents",
  "Agents critique each other with structured rebuttals",
  "Aggressive (most actions)",
  "Alibaba code model with strong performance",
  "Allow",
  "Allow autonomous mode to create new files",
  "Allow autonomous mode to edit existing files",
  "Allow autonomous mode to run bash commands (destructive commands always blocked)",
  "Allow command execution?",
  "Allow file read?",
  "Allow file write?",
  "Allow read of {0}?",
  "Allow write to {0}?",
  "Allow {0}?",
  "Alternative Install Methods",
  "An unexpected error occurred. Try running manually: {0}",
  "Analyze structure, patterns & conventions",
  "Analyzing...",
  "Answer questions using learned preferences",
  "Answers submitted",
  "Anthropic's Claude - powerful reasoning and code generation",
  "Approach",
  "Arcee AI",
  "Arcee AI's model optimized for agent harnesses",
  "Architect",
  "Architecture",
  "Ask Before Each Edit",
  "Ask Before Edit",
  "Ask Mysti to explain the current file, fix a bug, refactor a function, or write tests. Open files and selections can be included automatically when Auto Context is enabled.\n\n[Open Chat](command:mysti.openChat)",
  "Ask Mysti...",
  "Ask Permission",
  "Ask before edit",
  "Ask permission",
  "AskUserQuestion",
  "Attach",
  "Attach file...",
  "Attach files",
  "Attempt {0} failed, retrying...",
  "Audit licenses, accessibility & regulations",
  "Authenticate Provider",
  "Authenticate the Provider",
  "Authenticate: {0}",
  "Authenticating...",
  "Authentication",
  "Authentication Required",
  "Authentication skipped. You can configure providers manually in settings.",
  "Authentication successful!",
  "Authentication timed out. Please try again.",
  "Auto (Recommended)",
  "Auto Edit",
  "Auto-Commit",
  "Auto-Compact",
  "Auto-Suggest Personas",
  "Auto-accept on timeout",
  "Auto-approve edits to existing files within workspace",
  "Auto-approve most operations (destructive actions always blocked)",
  "Auto-approve safe file operations",
  "Auto-approved",
  "Auto-denied",
  "Auto-reject on timeout",
  "Auto-suggest",
  "Automatically approve the action when timeout expires",
  "Automatically deny the action when timeout expires",
  "Automatically documents non-obvious decisions and changes",
  "Automatically include open files and selections as context for better AI responses",
  "Automatically learn and remember project patterns across sessions (like Claude Code's auto-memory)",
  "Automatically start OpenClaw daemon if not running on extension activation",
  "Automatically stop discussion when agents reach consensus (reduces unnecessary rounds)",
  "Autonomous",
  "Autonomous Pioneer",
  "Autonomous coding agent with browser use, file editing, and command execution",
  "Autonomous session ended: {0} approved, {1} blocked, {2} questions answered, {3} tasks completed.",
  "Autonomous session ended: {0} questions answered, {1} tasks completed.",
  "Autonomy",
  "Available commands:",
  "Badge share text copied to clipboard!",
  "Baha Abunojaim",
  "Balanced (edits in workspace)",
  "Balanced Manus model",
  "Balanced thinking depth",
  "Balanced, no specific bias",
  "Behavior when permission request times out",
  "Best balance of speed and intelligence",
  "Best balance of speed, cost, and quality",
  "Best price-performance balance",
  "Better at coding and planning",
  "Block automatic shutdown when the agent has active child processes (requires explicit user action)",
  "Both agents collaborate",
  "Brainstorm",
  "Brainstorm (requires 2+ providers)",
  "Brainstorm Agents",
  "Brainstorm Synthesis",
  "Brainstorm mode disabled. Using Claude Code.",
  "Brainstorm mode enabled. Multiple agents will collaborate on your queries.",
  "Brainstorm mode is OFF. Using single agent.",
  "Brainstorm mode is ON. Multiple agents will collaborate.",
  "Brainstorm mode with two agents",
  "Brainstorm session failed",
  "Brainstorms",
  "Builder",
  "Builds internal tools that help the whole team move faster",
  "Builds reliable pipelines, deployments, and operational systems",
  "Builds the team by teaching, guiding, and supporting others",
  "Builds with the user experience as the north star",
  "CLI is not installed. Please install it first before authenticating.",
  "CLI not installed",
  "Can jump anywhere—frontend, backend, infra—and fill gaps",
  "Cancel",
  "Cancelled — new message sent",
  "Cannot reach npm registry. Check your internet connection.",
  "Change Codex CLI profile",
  "Change operation mode",
  "Change permission level",
  "Change the AI model",
  "Change the AI provider",
  "Changes:",
  "Channels",
  "Chat",
  "Chat history",
  "Check internet connection - cannot reach npm registry",
  "Check your internet connection and proxy settings. If behind a firewall, try: npm config list to verify proxy settings.",
  "Checking CLI installation...",
  "Checking authentication...",
  "Checking current status...",
  "Checking system requirements and permissions...",
  "Checking system requirements...",
  "Checking write permissions to npm global directory...",
  "Checking...",
  "Choose **Read Only**, **Ask Permission**, or **Full Access**. New users should start with **Ask Permission**; it keeps file changes under your control.\n\n[Open access settings](command:workbench.action.openSettings?%5B%22mysti.accessLevel%22%5D)",
  "Choose Authentication Method",
  "Choose File Access Level",
  "Choose Your Primary Provider",
  "Choose how to proceed",
  "Claude",
  "Claude Code",
  "Claude Code CLI (Anthropic) - Deep reasoning, complex refactoring, thorough analysis",
  "Claude Haiku 4.5",
  "Claude Opus 4.5",
  "Claude Opus 4.6",
  "Claude Sonnet 4",
  "Claude Sonnet 4 Thinking",
  "Claude Sonnet 4.5",
  "Clean Up",
  "Clear Context",
  "Clear context",
  "Clear conversation and session",
  "Clear persona",
  "Click the GitHub star link",
  "Click to change agent behavior",
  "Click to cycle brainstorm strategy",
  "Click to select a persona",
  "Cline",
  "Cline - Autonomous coding agent with browser use, file editing, and command execution",
  "Cline mode: {0}",
  "Close",
  "Code Llama",
  "Code Review",
  "CodeLens Action",
  "Codestral",
  "Codex",
  "Codex Profile",
  "Codex profile changed to: {0}",
  "Codex profile from ~/.codex/config.toml. Leave empty to use default profile.",
  "Collaboration strategy for brainstorm mode. Determines how agents interact as a team.",
  "Collector",
  "Command Failed",
  "Command timed out",
  "Command:",
  "Commands",
  "Commits incrementally with safe branching practices",
  "Communicates clearly without unnecessary verbosity",
  "Compact conversation context",
  "Compacted",
  "Compacting conversation...",
  "Compaction failed",
  "Compaction failed: {0}",
  "Complete",
  "Complete 10 autonomous sessions",
  "Complete provider setup",
  "Complete sign-in in the terminal that opened",
  "Complete {0} autonomous sessions",
  "Compliance",
  "Concise",
  "Configure at least two providers, then enable Brainstorm to let two agents independently analyze, challenge, and synthesize a solution.\n\n[Open Brainstorm settings](command:workbench.action.openSettings?%5B%22mysti.brainstorm.enabled%22%5D)",
  "Connected",
  "Cons",
  "Conservative (read + create only)",
  "Content Creator",
  "Context",
  "Context cleared",
  "Context usage percentage at which automatic compaction triggers (50-95%)",
  "Context usage:",
  "Context usage: 0%",
  "Context usage: {0}%",
  "Context usage: {0}k / {1}k tokens ({2}%) — Click to compact",
  "Context window size in tokens for Ollama (0 = use model default). Increase for longer conversations.",
  "Continue working without manual intervention",
  "Control what the AI can do with your files. Choose based on your trust level and task requirements.",
  "Convergence",
  "Conversation Files",
  "Conversation Sharer",
  "Conversation and session cleared",
  "Conversation compacted",
  "Conversation loaded: \"{0}\"",
  "Conversation not found",
  "Conversation too long for a deep link — full JSON copied to clipboard instead.",
  "Conversationalist",
  "Conversations",
  "Copied to clipboard!",
  "Copied!",
  "Copilot",
  "Copy",
  "Copy a shareable deep link to clipboard",
  "Copy command",
  "Copy conversation as Markdown",
  "Copy file path",
  "Copy message as Markdown",
  "Copy path",
  "Copy to Clipboard",
  "Copy to clipboard",
  "Could not load this conversation. The link may be invalid or expired.",
  "Create",
  "Create a custom file in your .mysti/ directory",
  "Create a custom persona",
  "Create a custom skill",
  "Created by",
  "Creates beautiful, accessible, and user-friendly interfaces",
  "Current Codex profile: {0}",
  "Current context:\n{0}",
  "Current context:\\n{0}",
  "Cursor",
  "Cursor - AI-powered coding with fast editing and multi-file changes",
  "Cursor API key. Set this instead of the CURSOR_API_KEY environment variable. Get your key from Cursor settings.",
  "Cursor picks the best model for each task. Works on all plans.",
  "Cursor's headless agent - AI-powered coding with fast editing and multi-file changes",
  "Custom model for Claude Code. Overrides the dropdown selection. Leave empty to use the selected model. Example: claude-sonnet-4-5-20250929",
  "Custom model for Cline. Overrides the dropdown selection. Leave empty to use the selected model. Example: claude-sonnet-4-5-20250929",
  "Custom model for Cursor. Overrides the dropdown selection. Leave empty to use the default model. Example: claude-sonnet-4-5-20250929",
  "Custom model for GitHub Copilot. Overrides the dropdown selection. Leave empty to use the selected model. Example: claude-opus-4.6",
  "Custom model for Google Gemini. Overrides the dropdown selection. Leave empty to use the selected model. Example: gemini-3-pro-preview",
  "Custom model for OpenAI Codex. Overrides the dropdown selection. Leave empty to use the selected model. Example: gpt-5.3-codex",
  "Custom model for OpenClaw. Overrides the dropdown selection. Leave empty to use the selected model. Example: claude-opus-4-6",
  "Custom model for OpenCode. Overrides the dropdown selection. Leave empty to use the default model. Example: anthropic/claude-sonnet-4-5",
  "Custom model for Qwen Code. Overrides the dropdown selection. Leave empty to use the default model. Example: qwen3-coder-plus",
  "Custom persona prompt for Claude (when persona is 'custom')",
  "Custom persona prompt for Cline (when persona is 'custom')",
  "Custom persona prompt for Codex (when persona is 'custom')",
  "Custom persona prompt for Copilot (when persona is 'custom')",
  "Custom persona prompt for Cursor (when persona is 'custom')",
  "Custom persona prompt for Gemini (when persona is 'custom')",
  "Custom persona prompt for LocalAI (when persona is 'custom')",
  "Custom persona prompt for Ollama (when persona is 'custom')",
  "Custom persona prompt for OpenClaw (when persona is 'custom')",
  "Custom persona prompt for OpenCode (when persona is 'custom')",
  "Custom persona prompt for Qwen Code (when persona is 'custom')",
  "Custom...",
  "Customize",
  "Customizer",
  "DEBUG: Simulated failure - npm not available on your system.",
  "DEBUG: Simulating installation...",
  "DEBUG: Simulating setup flow...",
  "DEBUG: This is a test auth prompt. Click Sign In or Later to test the flow.",
  "Day Streak",
  "Debate Champion",
  "Debug Issue",
  "Debug: Setup failure triggered",
  "Debug: Setup flow triggered",
  "Debug: Test Setup Failure",
  "Debug: Test Setup Flow",
  "Debugger",
  "Decline",
  "Dedicated",
  "Deep reasoning and analysis",
  "DeepMyst Inc.",
  "DeepSeek Coder V2",
  "DeepSeek R1",
  "DeepSeek V3",
  "Deeply understands the business problem and models it correctly",
  "Default",
  "Default (no customization)",
  "Default Model",
  "Default model to use",
  "Default operation mode",
  "Default thinking level for AI responses",
  "Delegated",
  "Delete",
  "Delphi Convergence",
  "Delphi Convergence - Facilitator-mediated iterative refinement",
  "Deny",
  "Dependency Aware",
  "Deprecated: Use mysti.brainstorm.maxDiscussionRounds instead.",
  "Deprecated: Use mysti.brainstorm.strategy instead. Kept for backward compatibility.",
  "Designer",
  "Designs the big picture and ensures everything fits together",
  "Detailed Plan",
  "Detect Connection",
  "Detect and show implementation plan options in AI responses. Disable to reduce post-response latency.",
  "Detected",
  "Detecting...",
  "DevOps Engineer",
  "Diagnose root cause & trace execution",
  "Direct install (recommended)",
  "Direct synthesis - faster, agents don't explicitly discuss",
  "Direct synthesis without discussion",
  "Direct synthesis without discussion (fastest)",
  "Disconnect",
  "Discussion",
  "Dismiss",
  "Display current context items",
  "Doc Reflexes",
  "Documentation",
  "Domain Expert",
  "Don't Ask Again",
  "Done",
  "Download Node.js →",
  "Downloading...",
  "Drop files here or click + to add context",
  "Drop images or files here",
  "Edit",
  "Edit Automatically",
  "Efficient open-source model by Mistral AI",
  "Enable",
  "Enable Autonomous Mode",
  "Enable agent lifecycle management with idle timeout and process tree protection",
  "Enable automatic context compaction when token usage exceeds the threshold",
  "Enable multi-agent brainstorm mode where two AI providers collaborate, debate, and synthesize solutions",
  "Enable token limit",
  "Enhance prompt",
  "Enhanced Qwen coding model",
  "Enhancement failed:",
  "Enhancement failed: {0}",
  "Enhancement timed out. Try again.",
  "Enhancing prompt...",
  "Enter model name (e.g. claude-sonnet-4-5-20250929)",
  "Error",
  "Error: {0}",
  "Esc to cancel",
  "Execute Automatically",
  "Exit plan mode",
  "Exited {0}. Switched to: ask-before-edit\n(Ready for implementation with {1})",
  "Exited {0}. Switched to: ask-before-edit\\n(Ready for implementation with {1})",
  "Expand/collapse",
  "Expired",
  "Explain this code",
  "Explain what the function `{0}` does:",
  "Export 10 conversations",
  "Export Conversation",
  "Export conversation as Markdown",
  "Export failed",
  "Export your first conversation",
  "Export {0} conversations",
  "Extended thinking for complex reasoning (paid plan required)",
  "Facilitator-mediated iterative convergence",
  "Failed",
  "Failed to import conversation: unrecognized format",
  "Failed to read:",
  "Failed to read: {0}",
  "Failed to revert",
  "Failed to revert {0}: {1}",
  "Failed to save conversation history",
  "Failed to start. Run: openclaw onboard --install-daemon",
  "Fast and capable via OpenClaw",
  "Fast and efficient for simpler tasks",
  "Fast and lightweight Manus model",
  "Fast and lightweight for quick tasks",
  "Fast multimodal understanding with strong reasoning",
  "Fast, high-quality coding model (paid plan required)",
  "Faster for writing and information seeking",
  "File deletion, destructive git ops, and irreversible actions are ALWAYS blocked.",
  "File too large (max",
  "File too large (max {0})",
  "File:",
  "Files",
  "Files:",
  "Find bugs",
  "Find bugs, anti-patterns & improvements",
  "Find vulnerabilities, secrets & attack vectors",
  "Finds the root cause of weird issues that block everyone else",
  "First Principles",
  "First Share",
  "First Words",
  "First commit with Mysti signature",
  "Fix npm permissions: npm config set prefix ~/.npm-global",
  "Flagship Anthropic model for complex tasks",
  "Focus on API design and UX",
  "Focus on code quality and issues",
  "Focus on code review and best practices",
  "Focus on implementation quality and performance",
  "Focus on practical implementation",
  "Focus on practical, working solutions",
  "Focus on system design and patterns",
  "Focus on technical correctness and performance",
  "Full Access",
  "Full access",
  "Full discussion - agents review and comment on each other's responses (maps to 'debate' strategy)",
  "Full setup with daemon",
  "Full-Stack Generalist",
  "GPT-4 (LocalAI)",
  "GPT-4.1",
  "GPT-5",
  "GPT-5 Mini",
  "GPT-5.1",
  "GPT-5.1 Codex",
  "GPT-5.1 Codex Max",
  "GPT-5.1 Codex Mini",
  "GPT-5.2",
  "GPT-5.2 Codex",
  "GPT-5.2 Instant",
  "GPT-5.2 Thinking",
  "GPT-5.3 Codex",
  "GPT4All-J",
  "Gemini",
  "Gemini 2.5 Flash",
  "Gemini 2.5 Flash Lite",
  "Gemini 2.5 Pro",
  "Gemini 3 Flash (Preview)",
  "Gemini 3 Pro (Preview)",
  "Gemini 3 Pro Preview",
  "Gemini GCA Setup",
  "General purpose model for professional tasks",
  "Get API keys at cursor.com/dashboard",
  "Get Started with Mysti",
  "Get your API key from Manus",
  "Getting Started",
  "GitHub Copilot",
  "GitHub Copilot CLI - GitHub-native AI assistant with seamless GitHub integration",
  "GitHub's Copilot - AI pair programmer with GitHub integration",
  "Goal or task description:",
  "Google",
  "Google Cloud Auth (GCA)",
  "Google Gemini",
  "Google Gemini CLI - Fast responses, Google ecosystem integration",
  "Google advanced reasoning model",
  "Google's Gemini - multimodal AI with code capabilities",
  "Google's latest model with 1M context (paid plan required)",
  "Graceful Degradation",
  "Great coding capability and subagent use",
  "Handles errors and edge cases without catastrophic failure",
  "Harden for reliability & operability",
  "Hide custom instructions",
  "Hide details",
  "Hide suggestions",
  "High",
  "How autonomous mode handles task continuation",
  "How long (in hours) to show file decoration badges after a file is modified by Mysti",
  "How long Ollama keeps the model loaded in memory after the last request (e.g., '5m', '1h', '0' to unload immediately).",
  "I've been Mysting and just earned the {0} {1} badge — {2}! #Mysting {3}",
  "Identify bottlenecks & optimize resources",
  "Idle",
  "If Mysti is useful, [star it on GitHub](https://github.com/DeepMyst/Mysti) and follow the project for updates.",
  "If Setup Does Not Work",
  "Import Conversation",
  "Import from .mysti.json, .json, or .jsonl file",
  "Imported Conversation",
  "Improve architecture & eliminate code smells",
  "In Progress",
  "Individual",
  "Individual Analysis",
  "Init Team Workspace",
  "Initialize team config for a workspace",
  "Input",
  "Install",
  "Install Automatically",
  "Install Node.js {0}+ from nodejs.org",
  "Install Provider",
  "Install npm (comes with Node.js from nodejs.org)",
  "Install the Provider CLI",
  "Install this provider to use it with Mysti.",
  "Install {0}",
  "Installation completed but CLI not found. You may need to restart your terminal or VS Code.",
  "Installation failed",
  "Installation failed after multiple attempts",
  "Installation failed. Try running the install command manually in a terminal: {0}",
  "Installation failed: {0}",
  "Installation timed out. Check your network speed and try again.",
  "Installing globally: {0}",
  "Installing {0} CLI...",
  "Installing...",
  "Integration",
  "Integrator",
  "Invalid characters. Use letters, numbers, dots, hyphens, underscores, colons, slashes.",
  "Invalid level. Available: {0}",
  "Invalid mode. Available modes: {0} (or 'plan' for quick-plan)",
  "Invalid profile name",
  "Invalid provider. Available: {0}",
  "JSON",
  "KAT Coder Pro",
  "Keep Planning",
  "KwaiKAT",
  "KwaiKAT's advanced agentic coding model",
  "Later",
  "Latest flagship model via OpenClaw",
  "Latest flagship model, most capable for complex tasks",
  "Leave a marketplace review",
  "Lightweight OpenAI coding model",
  "Lightweight OpenAI model",
  "Lightweight and cost-efficient for simple tasks",
  "Limit Agent Tokens",
  "Limit tokens used for agent context. Set to 0 for unlimited (default). Use lower values to reduce API costs.",
  "Living Legend",
  "Llama 3.2",
  "Llama2-based conversational model",
  "LocalAI",
  "LocalAI - Self-hosted OpenAI-compatible local inference with GPU/CPU support",
  "LocalAI API server URL (host and port)",
  "LocalAI model configured as gpt-4",
  "Low",
  "Luna AI Llama2",
  "Maintain a {0}-day usage streak",
  "Maintains clean file structures and follows project conventions",
  "Make {0} commits with Mysti signature",
  "Makes code cleaner, clearer, and more maintainable",
  "Makes different systems, APIs, and services work together",
  "Manual",
  "Manual Installation",
  "Manual install",
  "Manus 1.6",
  "Manus 1.6 Lite",
  "Manus 1.6 Max",
  "Markdown",
  "Maximum 10 attachments per message",
  "Maximum discussion rounds for debate and delphi strategies (may stop early with auto-converge)",
  "Maximum hours for an autonomous session (0 = unlimited)",
  "Maximum number of activity entries to display",
  "Maximum number of memory entries to store",
  "Maximum tokens to generate with LocalAI (0 = no limit). Useful for controlling response length.",
  "Maximum {0}",
  "Maximum {0} attachments per message",
  "Medium",
  "Megaphone",
  "Memory",
  "Mention file from project...",
  "Mentor",
  "Message not found",
  "Messages",
  "Meta code-specialized model",
  "Meta open-source model, good general purpose",
  "MiniMax M2.5",
  "Minimal extended thinking",
  "Minutes of inactivity before an agent session is automatically cleared (1-1440)",
  "Mistral",
  "Mistral's specialized coding model",
  "Mode",
  "Mode changed to: {0}",
  "Model",
  "Model changed to: {0}",
  "Model to use with LocalAI. Leave empty to use the default model.",
  "Model to use with Ollama (e.g., llama3.2, codellama, deepseek-coder). Leave empty to use the default model.",
  "Models: {0}",
  "Modified with Mysti ({0}) — {1}",
  "Most capable Manus model",
  "Most intelligent model for agents and coding",
  "Most intelligent, best for complex multimodal tasks",
  "Moves fast to test ideas and uncover unknowns",
  "Multi-agent AI coding assistant. Claude Code, Codex, Gemini, and GitHub Copilot brainstorm together, debate approaches, and deliver superior solutions. Like Cursor & Copilot, but with collaborative AI agents.",
  "My Badges",
  "Mysti",
  "Mysti - AI Coding Agent",
  "Mysti Ambassador",
  "Mysti JSON",
  "Mysti Logo",
  "Mysti access level settings",
  "Mysti can analyze code, execute tasks, and collaborate with you on complex projects.",
  "Mysti chat panel",
  "Mysti chat with AI response",
  "Mysti context workflow",
  "Mysti diagnostics and settings",
  "Mysti logo",
  "Mysti provider settings",
  "Mysti session activity\n{0}, {1}, {2}",
  "Mysti session activity\\n{0}, {1}, {2}",
  "Mysti settings...",
  "Mysti talks to provider CLIs installed on your machine. Install at least one supported CLI. The setup wizard can detect it and, where supported, help with installation.\n\n[Open Mysti setup](command:mysti.openChat)",
  "Mysti updated to v{0}! See what's new.",
  "Mysti v{0}",
  "Mysti wants to {0}: {1}",
  "Mysti will act on your behalf:",
  "Mysti · OpenClaw daemon not running",
  "Mysti · OpenClaw daemon running · {0} channels",
  "Mysti: Explain",
  "Mysti: OpenClaw Active",
  "Mysti: OpenClaw Offline",
  "Mysti: Refactor",
  "Mysti: Write Tests",
  "NVM",
  "Network",
  "New",
  "New Conversation",
  "New Tab",
  "New conversation",
  "Newest coding model, best for code generation",
  "No",
  "No CLI providers installed. Install at least one to get started.",
  "No Codex profile set",
  "No additional framing",
  "No changes",
  "No channels connected",
  "No context items added",
  "No extended thinking",
  "No global write permissions — installing to user directory (~/.mysti/cli)...",
  "No matching commands",
  "No models available for the current provider",
  "No persona",
  "No previous chats",
  "No recent activity",
  "No timeout - require explicit user action",
  "No workspace folder open.",
  "No workspace folder open. Open a project first.",
  "No write permission to npm global directory and local install failed.",
  "No write permission to npm global directory. Mysti installed to ~/.mysti/cli instead.\n\nTo install globally, either:\n• Run with sudo: sudo {0}\n• Fix npm permissions: npm config set prefix ~/.npm-global\n• See https://docs.npmjs.com/resolving-eacces-permissions-errors",
  "Node.js",
  "Node.js & npm",
  "Node.js Required",
  "Node.js is not installed",
  "Node.js {0}+ is required. Visit nodejs.org to install the latest LTS version, or run: nvm install --lts",
  "Node.js {0}+ required",
  "Node.js {0}+ required, found {1}",
  "None",
  "Not Found",
  "Not Installed",
  "Not Signed In",
  "Not authenticated",
  "Not currently in plan mode.",
  "Not enough conversation history to compact",
  "Not found",
  "Not installed",
  "Not installed - click Install to set up",
  "Not now",
  "ON",
  "OS",
  "Ollama",
  "Ollama - Local LLM inference server supporting Llama, CodeLlama, Mistral, and more",
  "Ollama API server URL (host and port)",
  "On a Roll",
  "One proposes, one challenges, then defense",
  "Only auto-approve read and create operations",
  "Open Chat",
  "Open Mysti",
  "Open Mysti extension settings",
  "Open Mysti from the Activity Bar or with ``Cmd+Shift+M`` (``Ctrl+Shift+M`` on Windows/Linux).\n\n[Open Mysti](command:mysti.openChat)",
  "Open Terminal & Authenticate",
  "Open documentation",
  "Open file",
  "Open file in editor",
  "Open in Browser",
  "Open in Editor Tab",
  "Open in Terminal",
  "Open in new tab",
  "Open the Mysti Panel",
  "Open the Mysti setup wizard and run diagnostics. Check that the selected CLI is installed, available in ``PATH``, authenticated, and matches the path configured in Mysti settings.\n\n[Open Mysti](command:mysti.openChat)",
  "Open-source GPT4All model",
  "Open-source personal AI assistant with multi-model support and Gateway streaming",
  "OpenAI",
  "OpenAI Codex",
  "OpenAI Codex CLI - Quick iterations, familiar GPT style, rapid prototyping",
  "OpenAI GPT-4.1 model",
  "OpenAI GPT-5 model",
  "OpenAI GPT-5 via OpenClaw",
  "OpenAI flagship coding model",
  "OpenAI general purpose model",
  "OpenAI o3",
  "OpenAI optimized for code generation",
  "OpenAI reasoning model (paid plan required)",
  "OpenAI's Codex - ChatGPT-powered code assistant",
  "OpenAI's latest flagship model (paid plan required)",
  "OpenClaw",
  "OpenClaw - Open-source personal AI assistant with multi-model support and Gateway streaming",
  "OpenClaw Active",
  "OpenClaw Active · {0} channels",
  "OpenClaw Offline",
  "OpenCode",
  "OpenCode - Multi-provider AI coding agent with support for OpenAI, Anthropic, Gemini, Groq, and OpenRouter",
  "Opening authentication...",
  "Operation mode",
  "Optimize",
  "Optimizes systems until they are fast, efficient, and smooth",
  "Option 1 (recommended): Run \"agent login\" to sign in with your Cursor account",
  "Option 1: Run \"codex auth login\" to sign in with ChatGPT account",
  "Option 1: Run \"gemini\" and sign in with your Google account",
  "Option 2: Set CURSOR_API_KEY in VS Code settings (mysti.cursorApiKey) or as environment variable",
  "Option 2: Set GEMINI_API_KEY environment variable",
  "Option 2: Set OPENAI_API_KEY environment variable",
  "Option 3: Set GOOGLE_GENAI_USE_GCA=true for Google Cloud subscribers",
  "Organized",
  "Output",
  "Partial",
  "Pass --verbose flag to CLI providers (Claude Code, Cline). Adds extra diagnostic output but may slow responses. Only enable for debugging.",
  "Path to Claude Code CLI executable",
  "Path to Cline CLI executable",
  "Path to Cursor CLI (agent) executable",
  "Path to GitHub Copilot CLI executable",
  "Path to Google Gemini CLI executable",
  "Path to OpenAI Codex CLI executable",
  "Path to OpenClaw CLI executable",
  "Path to OpenCode CLI executable",
  "Path to Qwen Code CLI executable",
  "Paused",
  "Performance",
  "Performance Tuner",
  "Permission Timeout",
  "Permission issue detected — installing to user directory...",
  "Persona",
  "Persona Crafter",
  "Persona Explorer",
  "Persona for Claude agent in brainstorm mode",
  "Persona for Cline agent in brainstorm mode",
  "Persona for Codex agent in brainstorm mode",
  "Persona for Copilot agent in brainstorm mode",
  "Persona for Cursor agent in brainstorm mode",
  "Persona for Gemini agent in brainstorm mode",
  "Persona for LocalAI agent in brainstorm mode",
  "Persona for Ollama agent in brainstorm mode",
  "Persona for OpenClaw agent in brainstorm mode",
  "Persona for OpenCode agent in brainstorm mode",
  "Persona for Qwen Code agent in brainstorm mode",
  "Perspective Lenses - Risk analysis vs. opportunity analysis",
  "Perspectives",
  "Pick the AI provider Mysti should use by default. You can change it later without changing any command or setting IDs.\n\n[Choose provider](command:workbench.action.openSettings?%5B%22mysti.defaultProvider%22%5D)",
  "Platform",
  "Please complete authentication in the terminal window",
  "Please select exactly 2 agents",
  "Polyglot",
  "Power User",
  "Prep Deployment",
  "Preparing your workspace...",
  "Previous Claude Sonnet model",
  "Previous flagship, advanced reasoning and analysis",
  "Previous gen flagship, supports context compaction",
  "Previous generation coding model",
  "Primary AI provider for coding assistance. Switch providers anytime without losing context.",
  "Primary Qwen coding model",
  "Product-Centric",
  "Production Ready",
  "Profile from ~/.codex/config.toml",
  "Progress",
  "Progress: {0} / {1}",
  "Project configured for Mysti. Created .mysti/, mysti.md, and rules/ — commit these so collaborators can discover Mysti.",
  "Pros",
  "Prototyper",
  "Provide a high-level goal and the agent continues until it's met",
  "Provide a list of tasks and the agent works through them sequentially",
  "Provider \"{0}\" not found",
  "Provider authentication",
  "Provider not found: {0}",
  "Provider setup",
  "Providers",
  "Question",
  "Queued",
  "Quick",
  "Quick - Direct synthesis without discussion (fastest)",
  "Quick Plan",
  "Quick Suggestions",
  "Qwen",
  "Qwen 2.5 Coder",
  "Qwen Code",
  "Qwen Code - Alibaba's AI coding agent with Qwen3-Coder models and multi-provider support",
  "Qwen's specialized coding model (480B A35B)",
  "Qwen3 Coder",
  "Qwen3 Coder Plus",
  "Rate Mysti",
  "Rate on Marketplace",
  "Read Only",
  "Read mysti.md and .mysti/rules/ for project-specific instructions (like CLAUDE.md)",
  "Read only",
  "Ready",
  "Ready to use!",
  "Ready!",
  "Reasoning-focused open-source model",
  "Reasons from fundamentals rather than pattern-matching",
  "Received",
  "Recommendations",
  "Recommended: 1000-4000",
  "Red Team",
  "Red Team - One agent proposes, the other challenges, then defense",
  "Refactor",
  "Refactor the function `{0}` for better readability and performance:",
  "Refactorer",
  "Reference a workspace file",
  "Refresh Detection",
  "Refreshing...",
  "Remind Me Later",
  "Remove",
  "Remove all context items",
  "Remove dead code, reorganize files & enforce hygiene",
  "Removed {0} line",
  "Removed {0} lines",
  "Repo Hygiene",
  "Report a bug on GitHub",
  "Report a problem",
  "Request timeout in milliseconds for LocalAI. Increase for large models or slow hardware.",
  "Request timeout in milliseconds for Ollama. Increase for large models or slow hardware.",
  "Require explicit action",
  "Requires 2+",
  "Requires 2+ installed providers",
  "Requires ChatGPT Plus/Pro subscription or API credits",
  "Requires npm installed on your system",
  "Researcher",
  "Reset to default",
  "Respects project dependencies and avoids unnecessary additions",
  "Retry",
  "Retrying...",
  "Return to VS Code once complete",
  "Revert",
  "Revert changes (git checkout)",
  "Reverted",
  "Reverted changes to {0}",
  "Reverting...",
  "Review",
  "Reviewer",
  "Risk analysis vs. opportunity analysis lenses",
  "Rollback Ready",
  "Round {0}",
  "Rules",
  "Run \"claude auth login\" in your terminal",
  "Run 10 brainstorm sessions",
  "Run 25 brainstorm sessions",
  "Run AI provider CLIs through the platform shell when required for CLI wrappers. On Windows, Mysti uses an explicit cmd.exe launcher instead of Node shell=true argument spawning.",
  "Run Diagnostics",
  "Run in Terminal",
  "Run the authentication command shown above",
  "Run this command to install {0}:",
  "Run {0} brainstorm sessions",
  "Run: {0}",
  "Running /compact via CLI",
  "Running diagnostics...",
  "Runs /compact to condense context when needed",
  "Safety Level",
  "Safety level for autonomous mode decisions",
  "Safety:",
  "Sampling temperature for LocalAI (0.0-2.0). Lower values produce more deterministic output.",
  "Sampling temperature for Ollama (0.0-2.0). Lower values produce more deterministic output.",
  "Scope Discipline",
  "Seconds before AI takes over in semi-autonomous mode. Applies to both permission requests and questions.",
  "Seconds between daemon status polls",
  "Seconds between process tree scans for idle sessions (10-300)",
  "Seconds to wait for permission approval (0 = no timeout, requires explicit action)",
  "Security Audit",
  "Security-Minded",
  "Select 2 agents for brainstorm mode",
  "Select AI agent",
  "Select Agent",
  "Select a model",
  "Select a provider",
  "Select access level",
  "Select an approach",
  "Select any 2 of 10 AI providers to collaborate in brainstorm mode. Different combinations offer unique strengths.",
  "Select files to attach",
  "Select how to authenticate with {0}",
  "Select one (optional)",
  "Select operation mode",
  "Select thinking level",
  "Select your first persona",
  "Semi-Auto",
  "Semi-Autonomous",
  "Send 2,000 messages",
  "Send 500 messages",
  "Send Your First Message",
  "Send message",
  "Send your first message",
  "Send {0} messages",
  "Sent",
  "Session",
  "Session cleared",
  "Set Up",
  "Set up .mysti/ config for your team",
  "Set up CI/CD, containers & infrastructure",
  "Set up Mysti step by step: provider, authentication, permissions, context, and multi-agent mode.",
  "Set up an AI provider to get started",
  "Setting up Mysti...",
  "Setting up providers and loading agents",
  "Settings",
  "Setup Failed",
  "Setup Wizard",
  "Setup complete!",
  "Setup failed",
  "Share 5 conversations via deep link",
  "Share 5 times",
  "Share Conversation",
  "Share link copied to clipboard!",
  "Share on X",
  "Share on X / Twitter",
  "Share {0} conversations via deep link",
  "Share {0} times",
  "Shell",
  "Ships features consistently, predictably, and reliably",
  "Show 'Mysti: Explain | Refactor | Write Tests' CodeLens above functions in the editor.",
  "Show Active Mode panel and connect to OpenClaw daemon automatically (provider-independent)",
  "Show after AI responses",
  "Show available commands",
  "Show context",
  "Show cross-channel activity feed in Active Mode panel",
  "Show current context items",
  "Show details",
  "Show extension version",
  "Show full output",
  "Show less",
  "Show more",
  "Show more...",
  "Show more... ({0} lines)",
  "Show quick action suggestions after AI responses",
  "Show sparkle 'M' badge on files modified by Mysti in the VS Code Explorer",
  "Show this help message",
  "Show/change AI model",
  "Show/change mode",
  "Sign In",
  "Sign in to the selected provider in its CLI. If Mysti reports an authentication problem, use **Run Diagnostics** in the setup wizard and follow the suggested command.\n\n[Open Mysti](command:mysti.openChat)",
  "Sign in to {0} to continue",
  "Sign in with ChatGPT",
  "Sign in with Cursor",
  "Sign in with Google",
  "Sign in with your Anthropic account",
  "Skill Smith",
  "Skills",
  "Skip",
  "Skip for now",
  "Slash commands",
  "Smart persona suggestions: Mysti analyzes your message and recommends the best persona (Architect, Debugger, etc.) for your task",
  "Solves hard technical problems using advanced theory and math",
  "Speed Demon",
  "Spread the Word",
  "Stable coding model, excellent for code tasks",
  "Star + Review + Share",
  "Star Gazer",
  "Star Mysti on GitHub",
  "Star on GitHub",
  "Start 50 conversations",
  "Start Daemon",
  "Start {0} conversations",
  "Starting...",
  "Stays focused on the task and resists scope creep",
  "Stop agent session",
  "Stop generating",
  "Strategist",
  "Strategy",
  "Strategy: {0}",
  "Strategy: {0} (click to cycle)",
  "Streaming...",
  "Strong code generation and understanding",
  "Strong open-source coding model",
  "Structured Debate",
  "Structured Debate - Agents critique each other's reasoning with rebuttals",
  "Structures changes to be easily reversible",
  "Structures work logically with clear separation of concerns",
  "Submit Answers",
  "Suggest based on message",
  "Suggested Fix",
  "Suggestions",
  "Summarizing older messages",
  "Support",
  "Sure",
  "Switch between plan and act modes",
  "Switch model...",
  "Switch profile",
  "Switch provider",
  "Switch provider...",
  "Switched to {0}",
  "Switched to {0} (model auto-switched to {1})",
  "Synthesis",
  "System Diagnostics",
  "Taking longer than expected...",
  "Tasks:",
  "Team Architect",
  "Team Builder",
  "Team Discussion",
  "Team Player",
  "Tell Mysti what to do instead...",
  "Test-Driven",
  "Thinking",
  "Thinking Level",
  "Thinking level",
  "Thinking level changed to: {0}",
  "Thinking level: {0}",
  "Thinks like an attacker to keep systems safe and compliant",
  "This CLI requires interactive setup. Run the command below in your terminal.",
  "This project has a Mysti configuration. Open Mysti to get started?",
  "Timeout",
  "To authenticate, run:",
  "To use {0}, you need to sign in. This will open your browser.",
  "Toggle",
  "Toggle Autonomous Mode",
  "Toggle OpenClaw integration on/off",
  "Toggle brainstorm mode",
  "Toggle multiple",
  "Toggle plan/act mode",
  "Token Budget",
  "Too long (max 128 characters)",
  "Too many @-mentions ({0}). Only the first {1} agent mentions will be processed.",
  "Tool:",
  "Tool: {0}",
  "Toolsmith",
  "Track child processes spawned by CLI agents to prevent premature shutdown",
  "Track when Mysti creates git commits for the Trail Blazer badge",
  "Trail Blazer",
  "Trinity Large",
  "Try 5 different personas",
  "Try Multi-Agent Brainstorm",
  "Try again",
  "Try all 5 collaboration strategies",
  "Try all {0} collaboration strategies",
  "Try all {0} persona categories",
  "Try restarting VS Code, or run the install command in a terminal and verify with: {0} --version",
  "Try {0} different AI providers",
  "Try {0} different personas",
  "Type your answer...",
  "URL of the OpenClaw Gateway WebSocket server",
  "Understand Project",
  "Unknown",
  "Unknown command: {0}",
  "Unknown error",
  "Unlock all required badges: Star, Review, and Share",
  "Unlocked",
  "Unlocked {0} — click to share",
  "Unreachable",
  "Unstoppable",
  "Use **Add to Context** from the editor or Explorer when a task depends on a specific file or selection. This makes the request more predictable and easier to review.\n\n[Open Mysti](command:mysti.openChat)",
  "Use 3 different AI providers",
  "Use Application Default Credentials for Cloud subscribers",
  "Use Mysti for 30 days",
  "Use Mysti for {0} days",
  "Use OpenClaw Gateway WebSocket for streaming (falls back to CLI if unavailable)",
  "Use This",
  "Use a Cursor API key from cursor.com/dashboard",
  "Use a Gemini API key from Google AI Studio",
  "Use all 7 providers",
  "Use an OpenAI API key",
  "Use custom prompt",
  "Use slash commands 50 times",
  "Use slash commands {0} times",
  "Use your ChatGPT Plus/Pro account",
  "Use your Cursor account (recommended)",
  "Use your Google account (recommended)",
  "Uses your OpenCode configured default model",
  "Verifying installation...",
  "Verifying local installation...",
  "Verifying network connectivity...",
  "Verifying npm availability...",
  "Verifying...",
  "Version",
  "Veteran",
  "View Documentation",
  "View and edit project memory (MEMORY.md)",
  "View and edit project rules (.mysti/rules/)",
  "View help docs",
  "Waiting for answer...",
  "Waiting for authentication...",
  "Waiting for reply...",
  "Waiting...",
  "Website",
  "Welcome to Mysti",
  "What happens when you don't respond to a permission request in time.",
  "What's New",
  "Working...",
  "Would you like to recommend Mysti to other contributors on this project?",
  "Write Tests",
  "Write comprehensive tests for the function `{0}`:",
  "Writes or updates tests alongside code changes",
  "Yes",
  "Yes, and don't ask again this session",
  "You can configure providers later in Settings",
  "You're Mysting with {0} — click to open chat",
  "You've been Mysting! {0}",
  "You've received {0} AI responses with Mysti! If you're enjoying it, would you consider leaving a review?",
  "Your AI Coding Agent",
  "Your AI coding team. Choose an action or ask anything!",
  "Your Stats",
  "Your answer",
  "active child processes",
  "ask-before-edit",
  "ask-permission",
  "automatically approved",
  "automatically denied",
  "bronze",
  "claude-code",
  "cline",
  "cursor",
  "detailed-plan",
  "e.g. Build a React dashboard with auth, CRUD, and tests",
  "edit-automatically",
  "full-access",
  "github-copilot",
  "gold",
  "google-gemini",
  "high",
  "in {0}s",
  "just now",
  "localai",
  "low",
  "manus",
  "medium",
  "none",
  "now",
  "npm",
  "npm (recommended)",
  "npm global dir writable",
  "npm is not available. Install Node.js from nodejs.org or use nvm.",
  "npm is not available. Install Node.js to enable automatic CLI installation.",
  "npm is not installed. Install Node.js from nodejs.org or use nvm (https://github.com/nvm-sh/nvm).",
  "o3",
  "o4-mini",
  "ollama",
  "openai-codex",
  "openclaw",
  "opencode",
  "platinum",
  "quick-plan",
  "qwen-code",
  "read-only",
  "seconds",
  "selection",
  "silver",
  "stars on GitHub",
  "sub-agent",
  "tokens",
  "web_search",
  "{0} (sub-agent)",
  "{0} (timeout)",
  "{0} Authentication",
  "{0} MB",
  "{0} attachments per message",
  "{0} channels",
  "{0} commands run",
  "{0} encountered an error: {1}",
  "{0} files",
  "{0} files edited",
  "{0} files read",
  "{0} in progress",
  "{0} in {1}",
  "{0} is not authenticated.",
  "{0} is ready!",
  "{0} items",
  "{0} lines",
  "{0} requires interactive setup and cannot be installed automatically. Please use the manual installation instructions.",
  "{0} skills",
  "{0}%",
  "{0}d ago",
  "{0}h ago",
  "{0}m ago",
  "{0}s",
  "↻ Refresh Detection",
  "⚠️ Taking longer than expected...",
  "✓ Pros",
  "✗ Cons",
  "📋 Copy to Clipboard",
  "📋 Select an approach",
  "📚 View Documentation",
  "🔍 Run Diagnostics",
  "🤖 AI will answer if no response",
  "🤖 AI will select an approach if no response",
] as const;

const WEBVIEW_PATTERNS: Array<{ source: string; regex: string }> = [
  {
    "source": "Show more... ({0} lines)",
    "regex": "^Show more\\.\\.\\. \\((\\d+) lines\\)$"
  },
  {
    "source": "Error: {0}",
    "regex": "^Error: (.+)$"
  },
  {
    "source": "{0} files",
    "regex": "^(\\d+) files$"
  },
  {
    "source": "AI {0} this action",
    "regex": "^AI (approved|denied) this action$"
  },
  {
    "source": "in {0}s",
    "regex": "^in (\\d+)s$"
  },
  {
    "source": "{0}s",
    "regex": "^(\\d+)s$"
  },
  {
    "source": "{0} skills",
    "regex": "^(\\d+) skills?$"
  },
  {
    "source": "{0} items",
    "regex": "^(\\d+) items?$"
  },
  {
    "source": "OpenClaw Active · {0} channels",
    "regex": "^OpenClaw Active · (\\d+) channels?$"
  },
  {
    "source": "Context usage: {0}%",
    "regex": "^Context usage: (\\d+)%$"
  },
  {
    "source": "{0} MB",
    "regex": "^(\\d+) MB$"
  },
  {
    "source": "Switched to {0}",
    "regex": "^Switched to (.+)$"
  },
  {
    "source": "Added {0} file(s) to context",
    "regex": "^Added (\\d+) file\\(s\\) to context$"
  }
  ,{
    "source": "Added {0} lines",
    "regex": "^Added (\\d+) lines?$"
  },
  {
    "source": "Removed {0} lines",
    "regex": "^Removed (\\d+) lines?$"
  },
  {
    "source": "{0} is not authenticated.",
    "regex": "^(.+) is not authenticated\\.$"
  }
] as const;

/**
 * Returns a CSP-safe webview bootstrap. It localizes static chrome and dynamic UI
 * while deliberately skipping user/assistant message bodies and code blocks.
 */
export function getWebviewLocalizationScript(): string {
  const dictionary: Record<string, string> = {};
  for (const message of WEBVIEW_MESSAGES) {
    dictionary[message] = vscode.l10n.t(message);
  }

  const patterns = WEBVIEW_PATTERNS.map(({ source, regex }) => ({
    regex,
    translated: vscode.l10n.t(source, '$1', '$2')
  }));

  return `
    (function mystiInstallLocalization() {
      const dictionary = ${JSON.stringify(dictionary)};
      const patterns = ${JSON.stringify(patterns)};
      const locale = ${JSON.stringify(vscode.env.language)};
      const skipSelector = '.message.user .message-content, .message.assistant .message-content, .thinking-content, .tool-input, .tool-output, pre, code, textarea';

      function translate(value) {
        if (!value || typeof value !== 'string') return value;
        const exact = dictionary[value];
        if (exact && exact !== value) return exact;
        for (const item of patterns) {
          const re = new RegExp(item.regex);
          if (re.test(value)) return value.replace(re, item.translated);
        }
        return value;
      }

      function format(source) {
        const args = Array.prototype.slice.call(arguments, 1);
        let template = translate(source);
        for (let i = 0; i < args.length; i++) {
          const value = args[i];
          if (value !== undefined && value !== null) {
            template = template.split('{' + i + '}').join(String(value));
          }
        }
        return template;
      }

      function shouldSkip(node) {
        const parent = node && node.nodeType === Node.ELEMENT_NODE ? node : node && node.parentElement;
        return !!(parent && parent.closest && parent.closest(skipSelector));
      }

      function localize(root) {
        if (!root || shouldSkip(root)) return;
        if (root.nodeType === Node.TEXT_NODE) {
          const raw = root.nodeValue || '';
          const leadingLength = raw.length - raw.trimStart().length;
          const trailingLength = raw.length - raw.trimEnd().length;
          const leading = leadingLength > 0 ? raw.slice(0, leadingLength) : '';
          const trailing = trailingLength > 0 ? raw.slice(raw.length - trailingLength) : '';
          const core = raw.trim();
          if (core) {
            const localized = translate(core);
            if (localized !== core) root.nodeValue = leading + localized + trailing;
          }
          return;
        }
        if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_NODE && root.nodeType !== Node.DOCUMENT_FRAGMENT_NODE) return;
        if (root.nodeType === Node.ELEMENT_NODE) {
          for (const attr of ['title', 'placeholder', 'aria-label']) {
            const current = root.getAttribute(attr);
            if (current) {
              const localized = translate(current);
              if (localized !== current) root.setAttribute(attr, localized);
            }
          }
        }
        const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
        const nodes = [];
        while (walker.nextNode()) nodes.push(walker.currentNode);
        for (const node of nodes) localize(node);
        if (root.querySelectorAll) {
          root.querySelectorAll('[title], [placeholder], [aria-label]').forEach(function(el) {
            if (!shouldSkip(el)) {
              ['title', 'placeholder', 'aria-label'].forEach(function(attr) {
                const current = el.getAttribute(attr);
                if (current) {
                  const localized = translate(current);
                  if (localized !== current) el.setAttribute(attr, localized);
                }
              });
            }
          });
        }
      }

      document.documentElement.lang = locale || 'en';
      localize(document.body);
      const observer = new MutationObserver(function(mutations) {
        for (const mutation of mutations) {
          if (mutation.type === 'characterData') localize(mutation.target);
          if (mutation.type === 'attributes') localize(mutation.target);
          mutation.addedNodes && mutation.addedNodes.forEach(localize);
        }
      });
      observer.observe(document.body, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: ['title', 'placeholder', 'aria-label'] });
      globalThis.mystiL10n = { translate, format, localize, locale };
    })();
  `;
}
